/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSurahsRouteImport } from './routes/_protected/surahs'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedAnotherPageRouteImport } from './routes/_protected/anotherPage'
import { Route as ProtectedStaffRouteRouteImport } from './routes/_protected/staff/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAdminResetPasswordRouteImport } from './routes/_protected/admin/reset-password'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSurahsRoute = ProtectedSurahsRouteImport.update({
  id: '/surahs',
  path: '/surahs',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAnotherPageRoute = ProtectedAnotherPageRouteImport.update({
  id: '/anotherPage',
  path: '/anotherPage',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStaffRouteRoute = ProtectedStaffRouteRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminResetPasswordRoute =
  ProtectedAdminResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/staff': typeof ProtectedStaffRouteRoute
  '/anotherPage': typeof ProtectedAnotherPageRoute
  '/profile': typeof ProtectedProfileRoute
  '/surahs': typeof ProtectedSurahsRoute
  '/admin/reset-password': typeof ProtectedAdminResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/staff': typeof ProtectedStaffRouteRoute
  '/anotherPage': typeof ProtectedAnotherPageRoute
  '/profile': typeof ProtectedProfileRoute
  '/surahs': typeof ProtectedSurahsRoute
  '/': typeof ProtectedIndexRoute
  '/admin/reset-password': typeof ProtectedAdminResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_protected/staff': typeof ProtectedStaffRouteRoute
  '/_protected/anotherPage': typeof ProtectedAnotherPageRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/surahs': typeof ProtectedSurahsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/admin/reset-password': typeof ProtectedAdminResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/staff'
    | '/anotherPage'
    | '/profile'
    | '/surahs'
    | '/admin/reset-password'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/staff'
    | '/anotherPage'
    | '/profile'
    | '/surahs'
    | '/'
    | '/admin/reset-password'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/reset-password'
    | '/_protected/admin'
    | '/_protected/staff'
    | '/_protected/anotherPage'
    | '/_protected/profile'
    | '/_protected/surahs'
    | '/_protected/'
    | '/_protected/admin/reset-password'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/surahs': {
      id: '/_protected/surahs'
      path: '/surahs'
      fullPath: '/surahs'
      preLoaderRoute: typeof ProtectedSurahsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/anotherPage': {
      id: '/_protected/anotherPage'
      path: '/anotherPage'
      fullPath: '/anotherPage'
      preLoaderRoute: typeof ProtectedAnotherPageRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/staff': {
      id: '/_protected/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof ProtectedStaffRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/reset-password': {
      id: '/_protected/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof ProtectedAdminResetPasswordRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminResetPasswordRoute: typeof ProtectedAdminResetPasswordRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminResetPasswordRoute: ProtectedAdminResetPasswordRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
  ProtectedStaffRouteRoute: typeof ProtectedStaffRouteRoute
  ProtectedAnotherPageRoute: typeof ProtectedAnotherPageRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSurahsRoute: typeof ProtectedSurahsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
  ProtectedStaffRouteRoute: ProtectedStaffRouteRoute,
  ProtectedAnotherPageRoute: ProtectedAnotherPageRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSurahsRoute: ProtectedSurahsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './app-start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
